#############################################################################
# Makefile for building: cmsc427
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  cmsc427.pro
# Template: app
# Command: /Users/ruoyu/Qt/5.8/clang_64/bin/qmake -o Makefile cmsc427.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -I/usr/local/include -stdlib=libc++ -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtXml.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/ruoyu/Qt/5.8/clang_64/lib
QMAKE         = /Users/ruoyu/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cmsc4271.0.0
DISTDIR = /Users/ruoyu/spring2017/cmsc427/Assignment-3-Mikhail-Sorokin-and-Ruoyu-Lei/.tmp/cmsc4271.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -stdlib=libc++ -Wl,-rpath,/Users/ruoyu/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/ruoyu/Qt/5.8/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GLview.cpp \
		cmsc427.cpp \
		Mesh.cpp qrc_resources.cpp \
		moc_GLview.cpp \
		moc_cmsc427.cpp
OBJECTS       = GLview.o \
		cmsc427.o \
		Mesh.o \
		qrc_resources.o \
		moc_GLview.o \
		moc_cmsc427.o
DIST          = ../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		cmsc427.pro GLview.hpp \
		cmsc427.hpp \
		Mesh.hpp GLview.cpp \
		cmsc427.cpp \
		Mesh.cpp
QMAKE_TARGET  = cmsc427
DESTDIR       = 
TARGET        = cmsc427


first: all
####### Build rules

$(TARGET): ui_cmsc427.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cmsc427.pro ../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		cmsc427.pro \
		resources.qrc \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.8/clang_64/lib/QtXml.framework/QtXml.prl \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile cmsc427.pro
../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.8/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.8/clang_64/mkspecs/features/lex.prf:
cmsc427.pro:
resources.qrc:
../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.8/clang_64/lib/QtXml.framework/QtXml.prl:
../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cmsc427.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GLview.hpp cmsc427.hpp Mesh.hpp $(DISTDIR)/
	$(COPY_FILE) --parents GLview.cpp cmsc427.cpp Mesh.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cmsc427.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../../Qt/5.8/clang_64/bin/rcc \
		wireframe.fsh \
		wireframe.vsh
	/Users/ruoyu/Qt/5.8/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -I/usr/local/include -stdlib=libc++ -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_GLview.cpp moc_cmsc427.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GLview.cpp moc_cmsc427.cpp
moc_GLview.cpp: ../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		Mesh.hpp \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		GLview.hpp \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/ruoyu/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ruoyu/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/ruoyu/spring2017/cmsc427/Assignment-3-Mikhail-Sorokin-and-Ruoyu-Lei -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtXml.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE' -I'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt' -I'C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\shared' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\um' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\winrt' -F/Users/ruoyu/Qt/5.8/clang_64/lib GLview.hpp -o moc_GLview.cpp

moc_cmsc427.cpp: ../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		ui_cmsc427.h \
		GLview.hpp \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		Mesh.hpp \
		cmsc427.hpp \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/ruoyu/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ruoyu/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/ruoyu/spring2017/cmsc427/Assignment-3-Mikhail-Sorokin-and-Ruoyu-Lei -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtXml.framework/Headers -I/Users/ruoyu/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE' -I'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt' -I'C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\shared' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\um' -I'C:\Program Files (x86)\Windows Kits\8.1\include\\winrt' -F/Users/ruoyu/Qt/5.8/clang_64/lib cmsc427.hpp -o moc_cmsc427.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cmsc427.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cmsc427.h
ui_cmsc427.h: cmsc427.ui \
		../../../Qt/5.8/clang_64/bin/uic \
		GLview.hpp \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		Mesh.hpp \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h
	/Users/ruoyu/Qt/5.8/clang_64/bin/uic cmsc427.ui -o ui_cmsc427.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

GLview.o: GLview.cpp GLview.hpp \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		Mesh.hpp \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLview.o GLview.cpp

cmsc427.o: cmsc427.cpp cmsc427.hpp \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		ui_cmsc427.h \
		GLview.hpp \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		Mesh.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmsc427.o cmsc427.cpp

Mesh.o: Mesh.cpp Mesh.hpp \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../Qt/5.8/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o Mesh.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_GLview.o: moc_GLview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLview.o moc_GLview.cpp

moc_cmsc427.o: moc_cmsc427.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmsc427.o moc_cmsc427.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

